language: ruby
sudo: required
warnings_are_errors: true

rvm:
  - 2.1
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx

env:
  - global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer