language: ruby
sudo: required
warnings_are_errors: true

rvm:
  - 2.1
script:
  - bundle exec jekyll build

env:
  - global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

notifications:
  email:
    on_success: change
    on_failure: change