# Site settings
title: City of Chicago Developers
owner: City of Chicago
email: developers@cityofchicago.org
description: > # this means to ignore newlines until "baseurl:"
  Explore City of Chicago APIs and get updated news for developers. 
url: "http://dev.cityofchicago.org" # directory containing site. Do not include trailing /
twitter_username: ChicagoCDO
github_username:  Chicago

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

paginate: 10
paginate_path: "blog/page:num"

exclude: [ "Gemfile.lock", "vendor"]
